# fly.toml app configuration file generated for shaw-n-partners-tht-frontend on 2024-05-13T21:57:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shaw-n-partners-tht-frontend'
primary_region = 'dfw'

[build]

[env]
  PORT = '4000'
  REACT_APP_API_URI = 'https://shaw-n-partners-tht-backend.fly.dev/'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
